name: Auto Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: torvalds
          base: master
          head: master
          auto_approve: false
          merge_method: merge
          pr_title: Auto Sync Fork
          pr_message: Actualización automática del Fork torvalds/linux
