name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make tinyconfig
      run: make tinyconfig
    - name: make
      run: make
    - name: make binrpm-pkg
      run: make binrpm-pkg
      
- name: Download a Build Artifact
  uses: actions/download-artifact@v2.0.6
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
    
