name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: RPMRC
      run: echo -e "buildarchtranslate:\ti386:\tx86_64\nbuildarchtranslate:\ti486:\tx86_64\nbuildarchtranslate:\ti586:\tx86_64\nbuildarchtranslate:\ti686:\tx86_64\nbuildarchtranslate:\tathlon:\tx86_64\nbuildarchtranslate:\tx86_64:\tx86_64" >> ~/.rpmrc

    - name: ARCH
      run: echo -e "%define arch x86_64\nBuildArch:\t%{arch}" >> ~/.rpmrc

    - name: cat
      run: cat ~/.rpmrc

    - name: Compile
      run: |
       rpm --eval '%{_target}'
       make tinyconfig
       make
       make binrpm-pkg
      
#    - run: mkdir -p /home/runner/rpmbuild/RPMS/i386/
#    - run: echo hola >/home/runner/rpmbuild/RPMS/i386/hola.txt
#    - run: ls -l /home/runner/rpmbuild/RPMS/i386/
      
    - uses: actions/upload-artifact@v2
      with:
        name: Compiled_Kernel
        path: ~/rpmbuild/RPMS/x86_64/
