name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo -e "buildarchtranslate:\ti386:\tx86_64" > /home/runner/.rpmrc
    - run: echo -e "buildarchtranslate:\ti486:\tx86_64" >> /home/runner/.rpmrc
    - run: echo -e "buildarchtranslate:\ti586:\tx86_64" >> /home/runner/.rpmrc
    - run: echo -e "buildarchtranslate:\ti686:\tx86_64" >> /home/runner/.rpmrc
    - run: echo -e "buildarchtranslate:\tathlon:\tx86_64" >> /home/runner/.rpmrc
    - run: echo -e "buildarchtranslate:\tx86_64:\tx86_64" >> /home/runner/.rpmrc

    - run: echo -e "%define arch x86_64" >> /home/runner/.rpmrc
    - run: echo -e "BuildArch:\t%{arch}" >> /home/runner/.rpmrc

    - run: cat /home/runner/.rpmrc

    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
       arch: ppc64le
       distro: fedora_latest
      - name: rpm eval
      - run: rpm --eval '%{_target}'
      - name: make tinyconfig
        run: make tinyconfig
      - name: make
        run: make
      - name: make binrpm-pkg
        run: make binrpm-pkg
      
#    - run: mkdir -p /home/runner/rpmbuild/RPMS/i386/
#    - run: echo hola >/home/runner/rpmbuild/RPMS/i386/hola.txt
#    - run: ls -l /home/runner/rpmbuild/RPMS/i386/
      
    - uses: actions/upload-artifact@v2
      with:
        name: Compiled_Kernel
        path: /home/runner/rpmbuild/RPMS/x86_64/
