name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make tinyconfig
      run: make tinyconfig
    - name: make
      run: make
    - name: make binrpm-pkg
      run: make binrpm-pkg
    - uses: actions/download-artifact@v2
      with:
      path: /home/runner/rpmbuild/RPMS/i386/
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /home/runner/rpmbuild/RPMS/i386/
