name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "build arch:x86_64" >/home/runner/.rpmrc
    - run: echo "compatible build archs:x86_64 noarch" >>/home/runner/.rpmrc
    - run: echo "build os:Linux" >>/home/runner/.rpmrc
    - run: echo "install arch:x86_64" >>/home/runner/.rpmrc
    - run: echo "install os:Linux" >>/home/runner/.rpmrc
    - run: echo "compatible os's:Linux" >>/home/runner/.rpmrc
    - run: cat /home/runner/.rpmrc
    - name: make tinyconfig
      run: make tinyconfig
    - name: make
      run: make
    - name: make binrpm-pkg
      run: make binrpm-pkg
      
#    - run: mkdir -p /home/runner/rpmbuild/RPMS/i386/
#    - run: echo hola >/home/runner/rpmbuild/RPMS/i386/hola.txt
#    - run: ls -l /home/runner/rpmbuild/RPMS/i386/
      
    - uses: actions/upload-artifact@v2
      with:
        name: Compiled_Kernel
        path: /home/runner/rpmbuild/RPMS/i386/
