name: Date

on:
  workflow_dispatch: # on button click

jobs:
  date:

    runs-on: ubuntu-20.04

    steps:
      - name: Date
        run: |
          date
          echo $PESONAL_TOKEN
          with:
            personal_token: ${{ secrets.PERSONAL_TOKEN }}
