name: Delete BUILDROOT

on:
  workflow_dispatch: # on button click

jobs:
  Delete:

    #runs-on: ubuntu-20.04
    runs-on: self-hosted

    steps:
      - name: Delete
        env:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          date
          rm -fr ~/rpmbuild/BUILDROOT/
          #echo $personal_token
