name: Fetch All

on:
  workflow_dispatch: # on button click.

jobs:
  fetch:

    runs-on: ubuntu-20.04

    steps:
    - name: fetch all
      run: |
        git init
        git remote add https://github.com/Quanticom/linux.git
        for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do
            git branch --track ${branch##*/} $branch
        done
        git fetch --all
        git pull --all
