name: sync_all_tags_branches

# File: .github/workflows/repo-sync.yml

on:
  workflow_dispatch: # on button click.

jobs:
  repo-sync_branches:
    runs-on: ubuntu-latest
    steps:
    - name: set-origin
      run: |
        git init
        git remote add origin git@github.com/torvalds/linux.git
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "torvalds/linux"
        source_branch: "refs/remotes/source/*"
        destination_repo: "Quanticom/linux"
        destination_branch: "refs/heads/*"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

#  repo-sync_tags:
#    runs-on: ubuntu-latest
#    steps:
#    - name: repo-sync
#      uses: wei/git-sync@v2
#      with:
#        source_repo: "torvalds/linux"
#        source_branch: "refs/tags/*"
#        destination_repo: "Quanticom/linux"
#        destination_branch: "refs/tags/*"
